name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
        SAST:
          runs-on: ubuntu-24.04
      
          steps:
            
            - name: Checkout Code
              uses: actions/checkout@v3
      
           
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16' 
      
           
            - name: Install Dependencies
              run: |
                npm install 
                if [ -d "./functions" ]; then
                 cd ./functions
                  npm install 
                cd ..
                fi
      
            
            - name: Configure SonarCloud Scanner
              run: |
                echo "sonar.projectKey=ALVAREZLEONARDO2392_labfinal" >> sonar-project.properties
                echo "sonar.organization=alvarezleonardo2392" >> sonar-project.properties
                echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
                echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-project.properties
                echo "sonar.sources=." >> sonar-project.properties
                echo "sonar.exclusions=**/node_modules/**" >> sonar-project.properties
                echo "sonar.javascript.packageManager=npm" >> sonar-project.properties
      
           
            - name: Run SonarCloud Scanner
              run: npx sonar-scanner
        SCA:
          runs-on: ubuntu-24.04
          needs: SAST
      
          steps:
            
            - name: Checkout Code
              uses: actions/checkout@v3

           
            - name: Install OWASP Dependency-Check
              run: |
                curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
                unzip dependency-check.zip
                chmod +x dependency-check*/bin/dependency-check.sh
            
            - name: Run OWASP Dependency-Check
              env:
                  NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
              run: |
                  dependency-check*/bin/dependency-check.sh \
                  --project "ALVAREZLEONARDO2392_labfinal" \
                  --scan . \
                  --format "ALL" \
                  --out odc-reports




          
            # - name: Run OWASP Dependency-Check
            #   run: |
            #     docker run --rm \
            #     -v $(pwd):/labfinal \
            #     -v $(pwd)/odc-reports:/report \
            #     owasp/dependency-check \
            #     --project "ALVAREZLEONARDO2392_labfinal" \
            #     --scan /labfinal \
            #     --format "ALL" \
            #     --out /report
            #     --nvdApiKey ${{ secrets.NVD_API_KEY }}
      
            
            - name: Upload Dependency-Check Report
              uses: actions/upload-artifact@v3
              with:
                name: dependency-check-report
                path: odc-reports/dependency-check-report.html
      

# jobs:
#   SAST:
#     runs-on: ubuntu-24.04
    
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v2
#         with:
#           java-version: '17'
#           distribution: 'adopt'

#       - name: Set enviroment variables
#         run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      

      # - name: Validate and configure build.gradle
      #   env:
      #     SONAR_TOKEN: $${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     if [ -f "package-lock.json" ]; then
      #       echo "Encontró el archivo"
      #       echo "Verificando configuración del plugin sonar"
      #       if ! grep -q 'id "org.sonarqube" version "3.3"' package-lock.json; then
      #         sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\' version '\''3.3'\''' package-lock.json
      #         echo "Plugin de Sonarcloud añadido en package json"
      #       else
      #         echo "Plugin de sonarcloud ya está configurado en package-lock.json"
      #       fi






            
      #       else
      #       echo "no se encontró archivo package-lock.json"
            
      #       exit 1
      #     fi