name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
        SAST:
          runs-on: ubuntu-24.04
      
          steps:
            # Step 1: Checkout the repository
            - name: Checkout Code
              uses: actions/checkout@v3
      
            # Step 2: Set up Node.js environment
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16' # Adjust Node.js version to match your project requirements
      
            # Step 3: Install project dependencies
            - name: Install Dependencies
              run: npm install
      
            # Step 4: Configure SonarCloud Scanner
            - name: Configure SonarCloud Scanner
              run: |
                echo "sonar.projectKey=your_project_key" >> sonar-project.properties
                echo "sonar.organization=your_organization" >> sonar-project.properties
                echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
                echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-project.properties
                echo "sonar.sources=." >> sonar-project.properties
                echo "sonar.exclusions=**/node_modules/**" >> sonar-project.properties
                echo "sonar.javascript.packageManager=npm" >> sonar-project.properties
      
            # Step 5: Run SonarCloud Scanner
            - name: Run SonarCloud Scanner
              run: npx sonar-scanner


# jobs:
#   SAST:
#     runs-on: ubuntu-24.04
    
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v2
#         with:
#           java-version: '17'
#           distribution: 'adopt'

#       - name: Set enviroment variables
#         run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      

      # - name: Validate and configure build.gradle
      #   env:
      #     SONAR_TOKEN: $${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     if [ -f "package-lock.json" ]; then
      #       echo "Encontró el archivo"
      #       echo "Verificando configuración del plugin sonar"
      #       if ! grep -q 'id "org.sonarqube" version "3.3"' package-lock.json; then
      #         sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\' version '\''3.3'\''' package-lock.json
      #         echo "Plugin de Sonarcloud añadido en package json"
      #       else
      #         echo "Plugin de sonarcloud ya está configurado en package-lock.json"
      #       fi






            
      #       else
      #       echo "no se encontró archivo package-lock.json"
            
      #       exit 1
      #     fi