name: workflow
on:
  push:
    branches:
      - main

jobs:
  SAST:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set enviroment variables
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Validate and configure build.gradle
        env:
          SONAR_TOKEN: $${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -f "package-lock.json" ]; then
            echo "Encontró el archivo"
            echo "Verificando configuración del plugin sonar"
            if ! grep -q 'id "org.sonarqube" version "3.3"' package-lock.json; then
              sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\' version '\''3.3'\''' package-lock.json
              echo "Plugin de Sonarcloud añadido en package json"
            else
              echo "Plugin de sonarcloud ya está configurado en package-lock.json"
            fi






            
            else
            echo "no se encontró archivo package-lock.json"
            
            exit 1
          fi