name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
        SAST:
          runs-on: ubuntu-24.04
      
          steps:
            
            - name: Checkout Code
              uses: actions/checkout@v3
      
           
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16' 
      
           
            - name: Install Dependencies
              run: |
                npm install 
                if [ -d "./functions" ]; then
                 cd ./functions
                  npm install 
                cd ..
                fi
      
            
            - name: Configure SonarCloud Scanner
              run: |
                echo "sonar.projectKey=ALVAREZLEONARDO2392_labfinal" >> sonar-project.properties
                echo "sonar.organization=alvarezleonardo2392" >> sonar-project.properties
                echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
                echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-project.properties
                echo "sonar.sources=." >> sonar-project.properties
                echo "sonar.exclusions=**/node_modules/**" >> sonar-project.properties
                echo "sonar.javascript.packageManager=npm" >> sonar-project.properties
      
           
            - name: Run SonarCloud Scanner
              run: npx sonar-scanner
        SCA:
          runs-on: ubuntu-latest
          needs: SAST
          name: Run the SCA scan on the source code
          steps:
            - uses: actions/checkout@master
            - name: RunSnyk to check for vulnerabilities
              uses: snyk/actions/maven@master
              continue-on-error: true
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

